### ISSUE TITLE
newline bug

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/to-clipboard#2]
related to https://github.com/jonschlinkert/to-clipboard/pull/1

**Comment by astoilkov** [comment]
First. This could be replicated under Windows and Mac (I haven't tested in Linux). This could be easily replicated by running the `to-clipboard` or just the command that is executed in terminal. Then click `Ctrl/Cmd + V` in a textarea for example(something that supports multiline) and you will see a new line pasted in the end. In terminal calling `echo -n` and the passed arguments after that fixes the problem both under Windows and Mac.

**Comment by jonschlinkert** [comment]
> This could be replicated under Windows and Mac (I haven't tested in Linux).

except I'm not getting the newline. perhaps it's my text editor settings? or zsh?

edit: I'm trying to figure out a fix. I know this is a legit bug, but something in my setup is probably preventing me from seeing it.

**Comment by astoilkov** [comment]
You could try virtual machine. Regarding the fix. I would suggest something similar to mine. You should add `-n` to the arguments of the `echo` call. This fixes the problem.

**Comment by tomsmeding** [comment]
Adding -n here doesn't work on my version of OSX. Might be my shell, but honestly, we shouldn't rely on people having a specific shell.

**Comment by astoilkov** [comment]
Hmm. Maybe it is more specific than I thought. It seems there should be done more investigation before fixing this issue.

**Comment by tomsmeding** [comment]
Since this seems to have been fixed some time ago already, and it works on linux, mac and termux (android), I'm going to close this issue. If anyone has problems on windows (which I can't test on at the moment), please feel free to open a new issue.
