### ISSUE TITLE
EONENT on Linux

### ISSUE THREAD

**Issue by AGhost-7** [jonschlinkert/to-clipboard#4]
Doesn't seem to work on linux.

**Comment by AGhost-7** [comment]
Fixed!

**Comment by jonschlinkert** [comment]
can you give more detail about what error you're experiencing? thanks

**Comment by AGhost-7** [comment]
It seems that `execSync` works fine for a single string with the arguments in it, but for `spawn` you need to place the arguments in an array:

https://nodejs.org/docs/v0.12.0/api/child_process.html#child_process_child_process_spawnsync_command_args_options

Here's the full trace:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn xclip -selection clipboard ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1054:32)
    at child_process.js:1145:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

In the case of Windows and Mac it doesn't matter since there are no arguments.

**Comment by tomsmeding** [comment]
Since the relevant PR has been merged, I'm closing this issue.

**Comment by tomsmeding** [comment]
You should now be able to change [this](https://github.com/AGhost-7/node-flip-table/blob/master/lib/to-clipboard.js#L5) to just `toClipboard(str)`. :)
